import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';

function CourseDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const [course, setCourse] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { fetch(`${API_URL}/courses/${id}`).then((response) => { if (!response.ok) throw new Error('Course not found.'); return response.json(); }).then(setCourse).catch((requestError) => setError(requestError.message)).finally(() => setLoading(false)); }, [id]);
  async function enroll() { const user = JSON.parse(localStorage.getItem('user') || 'null'); if (!user) { navigate('/login'); return; } setMessage(''); const response = await fetch(`${API_URL}/enrollments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ student_id: user.id, course_id: course.id }) }); const data = await response.json(); setMessage(response.ok ? 'You are enrolled successfully!' : data.message); }
  if (loading) return <main className="mx-auto max-w-7xl px-4 py-20 text-center text-slate-500">Loading course...</main>;
  if (error) return <main className="mx-auto max-w-7xl px-4 py-20 text-center"><p className="text-red-600">{error}</p><Link to="/courses" className="mt-5 inline-block font-semibold text-primary-500">Back to courses</Link></main>;
  return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><Link to="/courses" className="font-semibold text-primary-500">← All courses</Link><div className="mt-8 grid gap-10 lg:grid-cols-[1fr_360px]"><div><div className="flex h-72 items-center justify-center rounded-3xl bg-gradient-to-br from-primary-100 to-blue-200 text-8xl">📘</div><p className="mt-8 text-sm font-bold uppercase tracking-wider text-primary-500">{course.category?.name || 'General'} · {course.level}</p><h1 className="mt-3 text-4xl font-extrabold text-slate-900">{course.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{course.description}</p><h2 className="mt-10 text-2xl font-bold text-slate-900">Course curriculum</h2><div className="mt-4 space-y-3">{course.lessons?.map((lesson, index) => <div key={lesson.id} className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary-50 text-sm font-bold text-primary-500">{index + 1}</span><div><p className="font-semibold text-slate-800">{lesson.title}</p><p className="text-sm text-slate-500">{lesson.description || 'Course lesson'}</p></div></div>)}</div></div><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-soft"><p className="text-3xl font-extrabold text-slate-900">{Number(course.price) === 0 ? 'Free' : `$${course.price}`}</p><div className="mt-5 space-y-3 text-sm text-slate-600"><p>★ {course.rating || 'New'} rating</p><p>◉ {course.students_count || 0} students</p><p>◷ {course.duration || 'Self-paced'}</p><p>Instructor: {course.instructor?.name || 'LearnHub'}</p></div><button onClick={enroll} className="mt-7 w-full rounded-xl bg-primary-500 px-5 py-3 font-bold text-white hover:bg-primary-600">Enroll now</button>{message && <p className="mt-4 text-sm font-medium text-primary-600">{message}</p>}</aside></div></main>;
}
export default CourseDetails;
